### ISSUE TITLE
关于依赖YoukuPlayerOpenSDK第三方项目签名打包的问题

### ISSUE THREAD

**Issue by jerryzwork** [OptimalOrange/YoukuPlayerOpenSDK_android#1]
请问一下，我不签名打包调试运行，是可以正常调用播放器播放的，不过每次签名打包后，应用就无法启动了，是不是要在proguard-project.txt文件中加入什么啊？

**Comment by Bai-Jie** [comment]
我用commit e5038a3a3ec977d7cc95d6e6c54de35cf7551663 这种签名方法是可以正常运行的。
你那里有没有更具体的错误日志呢？

**Comment by jerryzwork** [comment]
![image](https://cloud.githubusercontent.com/assets/2508204/5991141/8cfa38f4-aa15-11e4-8ef7-a7ad2e549fdd.png)
就是，我用ant签名打包后，无法打开应用

**Comment by jerryzwork** [comment]
![qq 20150201132819](https://cloud.githubusercontent.com/assets/2508204/5991578/7fcb31ce-aa33-11e4-94d2-9b7969dadc4e.png)
![qq 20150201132828](https://cloud.githubusercontent.com/assets/2508204/5991579/83b665ce-aa33-11e4-8a7b-cce174331dd9.png)

**Comment by jerryzwork** [comment]
![image](https://cloud.githubusercontent.com/assets/2508204/5991933/cea099f4-aa49-11e4-8f1c-41e3e1bb1879.png)
最后，我发现，如果把这行注释起来，不混淆代码的话，打的包是可以正常启动应用的。如果我要加混淆的话，应该-keep哪些啊

**Comment by jerryzwork** [comment]
问题已解决：
如果要混淆的话，需要在“proguard-project.txt”中加入：

-keep class com.youku.**{*;}
-keep class org.openudid.**{*;}
-keep class com.v7.widget.**{*;}
-keep class cn.domob.android.**{*;}
-keep class cn.com.admaster.**{*;}
-keep class cn.com.mma.mobile.tracking.**{*;}
-keep class cn.com.mmachina.**{*;}
-keep class cn.com.iresearch.mapptracker.**{*;}
-keep class android.support.v7.**{*;}
-keep class com.inmobi.**{*;}
-keep class com.alibaba.fastjson.**{*;}
-keep class com.mobisage.android.**{*;}
-keep class com.punchbox.**{*;}
-keep class com.comscore.**{*;}
-keep class com.GitVersion {*;}
-keep class com.youdo.**{*;}
-keep class com.baseproject.**{*;}
-keep class com.decapi.**{*;}
-keep class com.luajava.**{*;}

使混淆打包时，对优酷依赖项目中所有相关的类不进行混淆，这样打出的包就可以正常运行了！
